baseurl = "https://nwdatascience.com"
title = "Northwest Data Science LLC - NWDS"
author = "Jameson Watts"
canonifyurls = true
paginate = 3
theme = "aether"

[params]
brand = "NWDS"
description = "Northwest Data Science LLC"
bgimg = "img/bg11.jpg"
homeimg = "img/home.jpg"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
